'use strict';

const test = require('node:test');
const assert = require('node:assert');
const { Merger, BEGIN_MARKER, END_MARKER, stripGeneratedSection } = require('../dist/merger');

const NEW_CONTENT = `# Generated section\n# Node\nnode_modules/\n*.log\n`;
const STACKS = ['node'];

test('Merger: fresh file wraps content in markers', () => {
  const m = new Merger();
  const out = m.buildFreshFile(NEW_CONTENT, STACKS);
  assert.ok(out.includes(BEGIN_MARKER));
  assert.ok(out.includes(END_MARKER));
  assert.ok(out.includes('node_modules/'));
});

test('Merger: merge with empty existing produces same as fresh', () => {
  const m = new Merger();
  const out = m.merge('', NEW_CONTENT, STACKS);
  assert.ok(out.includes(BEGIN_MARKER));
  assert.ok(out.includes(END_MARKER));
});

test('Merger: idempotency — running merge twice yields same content', () => {
  const m = new Merger();
  const first = m.merge('', NEW_CONTENT, STACKS);
  const second = m.merge(first, NEW_CONTENT, STACKS);
  assert.strictEqual(first, second);
});

test('Merger: preserves user content outside markers', () => {
  const m = new Merger();
  const existing = `# My personal rules\nsecret.json\n# vscode local\n.vscode/launch.local.json\n`;
  const out = m.merge(existing, NEW_CONTENT, STACKS);
  assert.match(out, /secret\.json/);
  assert.match(out, /\.vscode\/launch\.local\.json/);
  assert.match(out, /# My personal rules/);
});

test('Merger: drops user rules already in generated block (no duplicates)', () => {
  const m = new Merger();
  const existing = `# user\nnode_modules/\nsecret.json\n`;
  const out = m.merge(existing, NEW_CONTENT, STACKS);
  // node_modules/ should appear only once
  const matches = out.match(/^node_modules\/?$/gm) ?? [];
  assert.strictEqual(matches.length, 1, `expected 1 node_modules rule, got ${matches.length}\n${out}`);
  // secret.json kept
  assert.match(out, /secret\.json/);
});

test('Merger: handles trailing-slash differences as duplicates', () => {
  const m = new Merger();
  const existing = `node_modules\n`;
  const generated = `node_modules/\n`;
  const out = m.merge(existing, generated, STACKS);
  const matches = out.match(/node_modules\/?/g) ?? [];
  // 1 in generated section, 0 in user section
  assert.strictEqual(matches.length, 1, `expected single node_modules occurrence, got ${matches.length}\n${out}`);
});

test('Merger: replaces only between markers on re-run', () => {
  const m = new Merger();
  const existing = `# user comment\ncustom-rule\n`;
  const first = m.merge(existing, NEW_CONTENT, STACKS);
  // Now regenerate with different stacks/content
  const second = m.merge(first, `# Generated\n*.log\nbuild/\n`, ['java']);
  // node_modules from first run should be gone
  assert.ok(!second.includes('node_modules/'), 'old generated rule should not persist');
  // user content survives
  assert.match(second, /custom-rule/);
  assert.match(second, /# user comment/);
  // new generated content present
  assert.match(second, /build\//);
});

test('stripGeneratedSection: returns content unchanged when no markers/header', () => {
  const text = `# user\nfoo\nbar\n`;
  assert.strictEqual(stripGeneratedSection(text), text.trim());
});

test('stripGeneratedSection: removes legacy format', () => {
  const legacy = [
    '# Generated by smart-gitignore',
    '# Stacks: node',
    '',
    '# User comments:',
    '# my note',
    '',
    '# Generated rules:',
    'node_modules/',
    '*.log',
    '',
    '# Additional existing rules:',
    'custom-rule',
  ].join('\n');
  const cleaned = stripGeneratedSection(legacy);
  // Generated rules must be stripped
  assert.ok(!cleaned.includes('node_modules/'));
  assert.ok(!cleaned.includes('*.log'));
  // User content (additional rules + user comments) preserved
  assert.match(cleaned, /custom-rule/);
  assert.match(cleaned, /# my note/);
});

test('Merger: legacy format migrates cleanly on next run', () => {
  const m = new Merger();
  const legacy = [
    '# Generated by smart-gitignore',
    '# Stacks: node',
    '',
    '# Generated rules:',
    'node_modules/',
    '*.log',
    '',
    '# Additional existing rules:',
    'my-secret.json',
  ].join('\n');
  const out = m.merge(legacy, NEW_CONTENT, STACKS);
  // Markers now present
  assert.ok(out.includes(BEGIN_MARKER));
  assert.ok(out.includes(END_MARKER));
  // User-only rule preserved
  assert.match(out, /my-secret\.json/);
  // Single node_modules occurrence (in generated block)
  const matches = out.match(/^node_modules\/?$/gm) ?? [];
  assert.strictEqual(matches.length, 1);
});
