import * as fs from 'fs';
import { normalizePattern } from './normalize';
import { mergeBlocks } from './generator';

/**
 * Markers wrapping the auto-generated section.
 * Re-runs replace ONLY the content between markers, leaving everything
 * else (custom rules, custom comments) intact.
 */
export const BEGIN_MARKER = '# >>> smart-gitignore start (auto-generated; do not edit between markers)';
export const END_MARKER   = '# <<< smart-gitignore end';

/** Legacy header from versions <= 1.3.x (no markers). */
const LEGACY_HEADER = '# Generated by smart-gitignore';
const LEGACY_SECTION_TITLES = [
  '# User comments:',
  '# Generated rules:',
  '# Additional existing rules:',
];

/**
 * Idempotent merge of an existing .gitignore with newly generated content.
 *
 * Strategy:
 *   1. Strip any previously generated block (markers OR legacy format).
 *   2. Treat the remaining text as user-owned content; preserve verbatim.
 *   3. Emit: <generated block between markers> + blank line + <user content>.
 *   4. Run a final shared-policy dedup so user rules already present in the
 *      generated block are dropped from the user section (no duplicates).
 */
export class Merger {
  /**
   * Merges existing .gitignore with new content.
   */
  public merge(
    existingContent: string,
    newContent: string,
    detectedStacks: string[]
  ): string {
    const userContent = stripGeneratedSection(existingContent);
    const generatedBlock = wrapGenerated(newContent, detectedStacks);

    if (userContent.trim() === '') {
      return ensureTrailingNewline(generatedBlock);
    }

    // Final pass: drop any user-side line already covered by the generated
    // block (dedup uses the same shared policy as Generator.mergeTemplates).
    const dedupedUserContent = dedupAgainst(generatedBlock, userContent);

    if (dedupedUserContent.trim() === '') {
      return ensureTrailingNewline(generatedBlock);
    }

    return ensureTrailingNewline(`${generatedBlock}\n\n${dedupedUserContent.trim()}`);
  }

  /**
   * Generates the standalone header (used when no merge happens, kept for
   * backwards compatibility with existing callers in index.ts).
   */
  public generateHeader(stacks: string[]): string {
    return buildHeader(stacks) + '\n';
  }

  /**
   * Convenience wrapper: build the full file from scratch (no existing file).
   */
  public buildFreshFile(newContent: string, stacks: string[]): string {
    return ensureTrailingNewline(wrapGenerated(newContent, stacks));
  }

  public readExisting(gitignorePath: string): string {
    if (!fs.existsSync(gitignorePath)) return '';
    try {
      return fs.readFileSync(gitignorePath, 'utf-8');
    } catch (error) {
      throw new Error(`Error reading existing .gitignore: ${error}`);
    }
  }

  public write(gitignorePath: string, content: string): void {
    try {
      fs.writeFileSync(gitignorePath, content, 'utf-8');
    } catch (error) {
      throw new Error(`Error writing .gitignore: ${error}`);
    }
  }
}

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------

function buildHeader(stacks: string[]): string {
  const stacksList = stacks.join(',');
  return `# Generated by smart-gitignore\n# Stacks: ${stacksList}`;
}

function wrapGenerated(content: string, stacks: string[]): string {
  return [
    BEGIN_MARKER,
    buildHeader(stacks),
    '',
    content.trim(),
    '',
    END_MARKER,
  ].join('\n');
}

/**
 * Removes any previously generated block from the content, returning only
 * the user-owned portion. Handles both the marker-based format (current) and
 * the legacy "Generated by smart-gitignore" header without markers.
 */
export function stripGeneratedSection(content: string): string {
  if (content.trim() === '') return '';

  // Marker-based format: drop everything between BEGIN..END (inclusive).
  if (content.includes(BEGIN_MARKER) && content.includes(END_MARKER)) {
    const before = content.split(BEGIN_MARKER)[0];
    const afterPart = content.split(END_MARKER).slice(1).join(END_MARKER);
    return collapseBlankLines(`${before.trimEnd()}\n${afterPart.trimStart()}`).trim();
  }

  // Legacy format: drop the smart-gitignore header + section bodies, keep
  // user comments & "Additional existing rules:" pattern lines.
  if (content.includes(LEGACY_HEADER)) {
    return extractLegacyUserContent(content);
  }

  // No previous generated section: the whole file is user content.
  return content.trim();
}

function extractLegacyUserContent(content: string): string {
  const lines = content.split('\n');
  const userLines: string[] = [];
  // Modes:
  //   pre        — before the legacy header (treated as user content)
  //   header     — consuming "# Stacks:" / blanks right after the header
  //   user       — under "# User comments:" (keep comment lines)
  //   generated  — under "# Generated rules:" (drop everything)
  //   additional — under "# Additional existing rules:" (keep all rules)
  type Mode = 'pre' | 'header' | 'user' | 'generated' | 'additional';
  let mode: Mode = 'pre';

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed === LEGACY_HEADER) { mode = 'header'; continue; }
    if (mode === 'header') {
      if (trimmed.startsWith('# Stacks:') || trimmed === '') continue;
      // Header block ended without an explicit section title: treat as user.
      mode = 'user';
    }

    if (LEGACY_SECTION_TITLES.includes(trimmed)) {
      if (trimmed === '# User comments:') mode = 'user';
      else if (trimmed === '# Additional existing rules:') mode = 'additional';
      else mode = 'generated';
      continue;
    }

    if (mode === 'pre') {
      userLines.push(line);
      continue;
    }
    if (mode === 'user') {
      // Keep user comments and blank lines, drop accidental rule lines.
      if (trimmed.startsWith('#') || trimmed === '') userLines.push(line);
      continue;
    }
    if (mode === 'additional') {
      userLines.push(line);
      continue;
    }
    // mode === 'generated' -> discard
  }

  return collapseBlankLines(userLines.join('\n')).trim();
}

/**
 * Removes from `userContent` any rule already present (semantically) in
 * `generatedBlock`. Comments in user content are always preserved.
 */
function dedupAgainst(generatedBlock: string, userContent: string): string {
  const known = new Set<string>();
  for (const line of generatedBlock.split('\n')) {
    const key = normalizePattern(line);
    if (key && !key.startsWith('#')) known.add(key);
  }

  const out: string[] = [];
  for (const line of userContent.split('\n')) {
    const key = normalizePattern(line);
    if (key === null) {
      out.push(line);
      continue;
    }
    if (key.startsWith('#')) {
      out.push(line);
      continue;
    }
    if (!known.has(key)) {
      out.push(line);
      // Mark as known to dedupe within user content too.
      known.add(key);
    }
  }

  return collapseBlankLines(out.join('\n'));
}

function collapseBlankLines(content: string): string {
  return content.replace(/\n{3,}/g, '\n\n');
}

function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : content + '\n';
}

/**
 * Public utility to apply the shared dedup policy on raw text. Useful in
 * tests and future callers.
 */
export function dedupeContent(text: string): string {
  return mergeBlocks([text]);
}
